### ISSUE TITLE
is it Only Displayed Portrait? I want Displayed LandScape mode

### ISSUE THREAD

**Issue by lavarajallu** [d-a-n/react-native-modal-picker#41]
I want  a Land scape mode can you anyone tell me plz

**Comment by aamir-munir** [comment]
did you get it work on landscape?

**Comment by lavarajallu** [comment]
yes i got it

**Comment by aamir-munir** [comment]
can you please explain how :)

**Comment by erhanyil** [comment]
I have same issue... Can anybody help ? I couldn't find any solutions

**Comment by aamir-munir** [comment]
This component is not working with RN 0.43. scroll stop working if someone have solution please.

**Comment by cecampos** [comment]
For anyone with the same problems as me:
I corrected this problem using [this](https://github.com/d-a-n/react-native-modal-picker/pull/56) pending merge and reading [this](https://github.com/facebook/react-native/issues/7708) issue with the Modal component in RN.
The solution is fairly simple and consist on changing the styles to support % instead of numbers to make the modal responsive and adding the "supportedOrientations={['portrait', 'landscape']}" option inside the index.js.

**Comment by giorgio-ops** [comment]
Someone solved this problem ? I'm still facing this situation.

**Comment by mikaello** [comment]
@djpresent I have made an attempt to fix this. Check out the branch [peacechen/react-native-modal-selector#support-for-landscape-view](https://github.com/peacechen/react-native-modal-selector/tree/support-for-landscape-view) to test.

**Comment by mikaello** [comment]
Version 0.0.18 of [react-native-modal-selector](https://github.com/peacechen/react-native-modal-selector) supports landscape-view.
